version: '3'

services:
    backend:
        container_name: shotel_backend
        build: ./backend
        volumes:
            - ./backend/:/backend
        working_dir: /backend/
        command: pipenv run python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
