version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8
        environment:
          DEBUG: True
          SECRET_KEY: test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "backend/Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            cd backend
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "backend/Pipfile.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            mkdir test-results
            cd backend
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
