version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8
        environment:
          DEBUG: True
          SECRET_KEY: test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv flake8 isort
            cd backend
            pipenv install --dev
      - run:
          name: Test
          command: |
            cd backend
            pipenv run python manage.py test
            isort --diff --check-only
            flake8 --show-source --statistics \
              --max-line-length=120 \
              --per-file-ignores="__init__.py:F401" \
              --exclude=*migrations*,*settings* ./
